services:
  rabbitmq:
    image: rabbitmq:4-management-alpine
    container_name: rabbitmq_dev
    ports:
        - 5672:5672
        - 15672:15672
    volumes:
        - rabbitmq_data:/var/lib/rabbitmq/
        - rabbitmq_logs:/var/log/rabbitmq
    env_file:
      - .env

  postgres_db:
    image: postgres:17-alpine
    container_name: pgsql_dev
    ports:
        - 5432:5432
    volumes:
      - postgres_data:/var/lib/postgresql/data
    env_file:
      - .env

volumes:
  rabbitmq_data: {}
  rabbitmq_logs: {}
  postgres_data: {}
