[project]
name = "taskiq-pgsql-rabbitmq"
version = "0.1.0"
description = "TaskIQ with PgSQL and RabbitMQ"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "taskiq==0.11.7",
    "taskiq-aio-pika==0.4.1",
    "psqlpy==0.8.1",
]
